const express = require('express');
const app = express();

app.use(express.json());

app.get('/health', (req, res) => {
  res.json({ status: 'API is running' });
});

// Create a new user.
app.post('/users', (req, res) => {
    // id of the user must be generated by the server
    // TO IMPLEMENT
})

// Get users list.
app.get('/users', (req, res) => {
    // TO IMPLEMENT
})

// ANOTHER ENDPOINTS COULD BE NECESSARY


module.exports = app;